Palyer move feature branch
Arslan909/tic_tac_toe pull request #2
Opened 2023-03-29 05:06 UTC by MTS999

create a funtion for  change move and also included valid check ( same function)

2023-03-29 05:12 UTC, MTS999 commented
ps: also changed struct structure.add char veriable player ( ("X")||("O")
to make palyer shift functionality

2023-03-29 10:29 UTC, shasherazi requested changes
See the comments.

2023-03-29 10:29 UTC, shasherazi commented on include/board.c
> +    }
`turn` is only going to be either `1` or `0`. I'd suggest that instead of incrementing `turn` after every turn just toggle it.

2023-03-29 10:29 UTC, shasherazi commented on include/board.c
> +    scanf(" %d", &temp);
Please keep the functions pure i.e. without any [side effects](https://medium.com/nerd-for-tech/what-are-side-effects-in-programming-51f7ef340f98). `make_move` function should only update the `struct Board` and not take any input or print any output.

2023-03-30 07:44 UTC, shasherazi requested changes
`board.c` file implements the functions declared in `board.h`. Please use the declarations and the Board struct defined in `board.h` and just implement the functions without worrying about input/output.

2023-03-30 10:19 UTC, shasherazi requested changes
See the comments

2023-03-30 10:19 UTC, shasherazi commented on include/board.c
> -            board->board[i][j] = EMPTY;
I'd say let the already defined function be as they were before i.e. `init_board` and `print_board`.

2023-03-30 10:19 UTC, shasherazi commented on include/board.c
> +    }
You already have the `row` and `col` parameters, no need to loop.

2023-03-30 10:19 UTC, shasherazi commented on include/board.c
> +    }
It will be conciser if you use a ternary statement here.

2023-03-30 10:19 UTC, shasherazi commented on include/board.h
> +    char turn;
Good call, it should've been `char` from the beginning.

2023-03-30 12:09 UTC, shasherazi commented on include/board.c
> +}
Explain what this function is doing and returning?

2023-03-30 12:24 UTC, MTS999 commented on include/board.c
> +}
if touched box'text is 'X' or 'O'  function will return zero (invalid move)
else valid move

2023-03-30 12:32 UTC, taimoor-shahid commented on include/board.c
> +}
*selected box

2023-03-31 08:22 UTC, merged